version: "3.4"
services:
  web-server:
    volumes:
      - ./web_server/:/mnt/
      - ./files/:/files/
    build: ./web_server
    working_dir: /backend
    command: sh run.sh
    env_file:
      - 'variables.env'
    networks:
      - default
    ports:
      - 5000:80
    depends_on:
      - db

  worker:
    volumes:
      - ./worker/:/mnt/
      - ./files/:/files/
    build: ./worker
    working_dir: /backend
    command: sh run.sh
    env_file:
      - 'variables.env'
    networks:
      - default
    ports:
      - 5001:5000
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'convertion'
      MYSQL_USER: 'convertion'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./dbdata:/var/lib/mysql
