version: "3.2"
services:
  web-server:
    volumes:
      - ./web_server/:/mnt/
      - ./files/:/files/
    build: ./web_server
    working_dir: /backend
    command: sh run.sh
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - 5000:5000
    depends_on:
      - db

  worker:
    volumes:
      - ./worker/:/mnt/
      - ./files/:/files/
    build: ./worker
    working_dir: /backend
    command: sh run.sh
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - 5001:5000

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
